# Generated by Django 5.2.17 on 2026-09-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('Español', 'Español'), ('Lengua indígena', 'Lengua Indígena'), ('Ingles', 'Inglés'), ('Frances', 'Francés')], help_text='Select the book language', max_length=30),
        ),
    ]
